image: python:3.5

stages:
    - build
    - test
    - deploy
#    - review
    

before_script: 
    #~ - apt-get update && apt-get -y install gcc libmagickwand-dev make
    - pip3 install -U pip setuptools wheel
    - pip3 install -r requirements.txt
    - python3 setup.py build_ext -i #Need the C++ extension only.
    - mkdir testpath

after_script:
    - rm -rf dist build docs/build openlut.egg-info

build:
    stage: build
    script:
        - python3 setup.py sdist #Build source distribution.
        - python3 setup.py bdist_wheel #Build Linux wheel.
    artifacts:
        paths:
            - dist
            
# run tests using the binary built before.

build_docs:
    stage: build
    script:
        - ./mkDocs.sh
    artifacts:
        paths:
            - docs/build/html

test:
    stage: test
    script:
        - python3 tests/suite.py
        
deploy_docs:
    stage: deploy
    environment:
        name: Documentation
        url: https://www.sofusrose.com/openlut
    script:
        - docs/upload.sh
    #~ when: manual
    

        
