image: python:3.5

stages:
    - build
    - test
    #~ - deploy
#    - review
    

before_script: 
    - wget https://github.com/git-lfs/git-lfs/releases/download/v1.5.5/git-lfs-linux-amd64-1.5.5.tar.gz && tar xf git-lfs-linux-amd64-1.5.5.tar.gz && cd git-lfs-1.5.5/ && ./install.sh
    - git lfs install
    - pip3 install -U pip setuptools wheel
    - pip3 install -r requirements.txt
    - python3 setup.py build_ext -i #Need the C++ extension only.
    - mkdir testpath

build:
    stage: build
    script:
        - python3 setup.py sdist #Build source distribution.
        - python3 setup.py bdist_wheel #Build Linux wheel.
    artifacts:
        paths:
            - dist
            
# run tests using the binary built before.

build_docs:
    stage: build
    script:
        - ./mkDocs.sh
    artifacts:
        paths:
            - docs/build/html

test:
    stage: test
    script:
        - git lfs pull
        - python3 tests/suite.py
        
#~ deploy_docs:
    #~ stage: deploy
    #~ environment:
        #~ name: Documentation
        #~ url: https://www.sofusrose.com/openlut
    #~ script:
        #~ - docs/upload.sh
    #~ when: manual
    

        
